### ISSUE TITLE
Ability to print a 'report' of all defined tests via CLI

### ISSUE THREAD

**Issue by UgiR** [UgiR/gradescope-autograde-cpp#10]
If there are many test directories, it can get difficult to get a grasp of all defined test configuration without going through each directory and looked at each config file. Instead, there should be a CLI command that simply prints a brief report of all defined tests.

For example:

```
./grader report -a

my_test1:
  weight: 15
  name: 'BST balancing'
  message: 'insert() must maintain a balanced BST' 
  show_output: false
  timeout: 10
  visibility: hidden
my_test2:
  weight: 15
  name: 'BST balancing'
  message: 'insert() must maintain a balanced BST' 
  show_output: false
  timeout: 10
  visibility: hidden
```
